# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory
set_property part xc7vx485tffg1157-1 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog {
  /home/jheckey/Dropbox/homework/ece253/spartan_tetris/vga/vga.v
  /home/jheckey/Dropbox/homework/ece253/spartan_tetris/vga/siggen.v
  /home/jheckey/Dropbox/homework/ece253/spartan_tetris/vga/tb.v
}
set_property webtalk.parent_dir /home/jheckey/Dropbox/homework/ece253/spartan_tetris/vga/vga/vga.data/wt [current_project]
set_property parent.project_dir /home/jheckey/Dropbox/homework/ece253/spartan_tetris/vga/vga [current_project]
synth_design -top tb -part xc7vx485tffg1157-1
write_checkpoint tb.dcp
report_utilization -file tb_utilization_synth.rpt
